# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
env:
  es6: true

parser: "@typescript-eslint/parser"

plugins: ["@typescript-eslint"]

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"

settings:
  "import/resolver":
    typescript:
      alwaysTryTypes: true

rules:
  "@typescript-eslint/no-unused-vars": ["error"]
  no-console: ["error"]
  no-debugger: ["error"]
